-- Create sensor_readings table
CREATE TABLE IF NOT EXISTS public.sensor_readings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id TEXT NOT NULL,
    latitude FLOAT NOT NULL,
    longitude FLOAT NOT NULL,
    ax FLOAT DEFAULT 0,
    ay FLOAT DEFAULT 0,
    az FLOAT DEFAULT 0,
    src TEXT DEFAULT 'GPS',
    p_dist FLOAT DEFAULT 0,
    pair_id INT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.sensor_readings ENABLE ROW LEVEL SECURITY;

-- Create policies for public access (adjust as needed for security)
CREATE POLICY "Public can read sensor readings" ON public.sensor_readings
    FOR SELECT
    USING (true);

CREATE POLICY "Public can insert sensor readings" ON public.sensor_readings
    FOR INSERT
    WITH CHECK (true);

-- Create a view for the latest device locations
CREATE OR REPLACE VIEW public.latest_device_locations AS
SELECT DISTINCT ON (device_id) *
FROM public.sensor_readings
ORDER BY device_id, created_at DESC;

-- Grant permissions (if needed, though typically default for authenticated/anon roles)
GRANT SELECT, INSERT ON public.sensor_readings TO anon, authenticated, service_role;
GRANT SELECT ON public.latest_device_locations TO anon, authenticated, service_role;
